### ISSUE TITLE
Use with /* webpackChunkName: "-----" */ 

### ISSUE THREAD

**Issue by Glidias** [cheap-glitch/vue-cli-plugin-sitemap#1]
Does this work with eg. `component: /* webpackChunkName: "blahblah" */ ` for dynamically loaded component routes? Likely not and a workaround would be needed for that i guess.

**Comment by cheap-glitch** [comment]
> Does this work with eg. component: /* webpackChunkName: "blahblah" */ for dynamically loaded component routes?

It does, I have a setup in one of my projects with `vue-router` + dynamically loaded components + explicit chunk splitting and it works fine.

When dealing with an array of routes the plugin will totally ignore the `component` and `components` properties on the routes objects, as the only useful prop to generate the sitemap is `path` (and some optional plugin-specific meta props, as documented in the readme).

Closing this issue for now, if you do try this kind of setup and run into some problems feel free to reopen it.
