### ISSUE TITLE
Support for 'hash' router mode

### ISSUE THREAD

**Issue by DJWoodZ** [cheap-glitch/vue-cli-plugin-sitemap#14]
Hi there,

This is a great project. Thank you.

I have a project which has to use the 'hash' router mode, but the hash (`#`) symbol isn't automatically added to the URLs in the generated sitemap.

If I add the `#` symbol to the `baseURL` option, I get errors about it not matching the expected pattern. Am I doing something wrong?

If not, would it be possible to add support for the 'hash' router mode and allow the `#` symbol to be used in the `baseURL` please?

Thanks.

**Comment by cheap-glitch** [comment]
Thank you for the feature request!

I added a `hashMode` option to the plugin, set it to `true` and an hashtag will automatically be added to the URL where needed.

Feel free to re-open this issue if you still have a problem with this.
