### ISSUE TITLE
Installing plugin runs eslint --fix unexpectedly

### ISSUE THREAD

**Issue by unikitty37** [cheap-glitch/vue-cli-plugin-sitemap#18]
After installing the plugin, when the generator is invoked, it seems to be running `eslint --fix` on my code, despite the fact that:

a) I did not ask it to
b) I have `lintOnSave: false` in `vue.config.js`

I can't find any reference to this in the source, though, apart from the presence of a .eslintrc (and it does appear to be using my settings, and not the project's).

Is this something that the plugin is doing, or is it Vue (version 2.6.11) itself being odd?

(Also, was that the last step in the generator process? Has something been left incomplete by that eslint error?)

```
└─▷ vue add sitemap

📦  Installing vue-cli-plugin-sitemap...

yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
└─ vue-cli-plugin-sitemap@2.3.0
info All dependencies
├─ code-error-fragment@0.0.230
├─ grapheme-splitter@1.0.4
├─ json-to-ast@2.1.0
├─ jsonpointer@4.1.0
└─ vue-cli-plugin-sitemap@2.3.0
✨  Done in 83.00s.
✔  Successfully installed plugin: vue-cli-plugin-sitemap


🚀  Invoking generator for vue-cli-plugin-sitemap...
⠋  Running completion hooks...error: 'itDoesNotAllowAnyFeedsToBeSynced' is assigned a value but never used (no-unused-vars) at tests/e2e/integration/calendar_feeds_spec.js:224:7:
  222 | }
  223 |
> 224 | const itDoesNotAllowAnyFeedsToBeSynced = () => {
      |       ^
  225 |   cy.get('.calendar-feeds table tbody tr button')
  226 |     .contains('Sync')
  227 |     .should('not.exist')


1 error found.
```

**Comment by cheap-glitch** [comment]
This shouldn't happen, and it's definitely not intended! The culprit is probably Vue CLI, but I'll have to investigate.

> Also, was that the last step in the generator process? Has something been left incomplete by that eslint error?

As it says in the readme (and you can verify it [here](https://github.com/cheap-glitch/vue-cli-plugin-sitemap/blob/main/generator.js)), the generator only adds an npm script to `package.json`. (Looking back on it it's kinda pointless, I'll probably remove the generator altogether when I rewrite this plugin in TypeScript.)
