### ISSUE TITLE
Use without Vue CLI

### ISSUE THREAD

**Issue by Nisgrak** [cheap-glitch/vue-cli-plugin-sitemap#19]
Hi!

I'm a big fan of [quasar](https://quasar.dev), it's have his own cli and would be cool to allow use this plugins without the Vue CLI requisite, so anyone can use it.

Thanks in advance 😄

**Comment by cheap-glitch** [comment]
Hi,
I'm planning on rewriting this plugin in TS, and to that end I extracted the main functionality into a [separate Node module](https://github.com/cheap-glitch/planisphere). It's yet undocumented but the API is the largely the same (you can look at [the test cases](https://github.com/cheap-glitch/planisphere/blob/main/test/index.test.ts) to see some practical examples).

**Comment by Nisgrak** [comment]
But it's ready now?

**Comment by cheap-glitch** [comment]
> But it's ready now?

It's basically finished, it just needs to be documented.
