### ISSUE TITLE
outputDir option?

### ISSUE THREAD

**Issue by Glidias** [cheap-glitch/vue-cli-plugin-sitemap#2]
There is not outputDir option to set output location to diff folder? Upon attempt, i get `[vue-cli-plugin-sitemap]: options should NOT have additional properties`

**Comment by cheap-glitch** [comment]
Added the `outputDir` option in [1.0.4](https://github.com/cheap-glitch/vue-cli-plugin-sitemap/releases/tag/v1.0.4). Note that by default, the plugin will follow the global `outputDir` option set in `vue.config.js`.
