### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by pianistprogrammer** [cheap-glitch/vue-cli-plugin-sitemap#25]
```
/Users/mysuer/Desktop/project/src/views/Home.vue:1
<template>
^
```
I get this error after running npm run sitemap, I am confused as the build `npm run build` runs successfully
Can someone help with this please?

**Comment by cheap-glitch** [comment]
This is probably because you imported/required a Vue file in your `vue.config.js` (or you imported a `.js` file which in turns import a `.vue` file). Importing anything other than `.js(on)` files (or anything that resolves to it) is a Webpack feature and will never work with Node.js.

The simplest fix is to define your routes in a plain JS module with no static imports (or JS-only imports), and use [dynamic imports](https://router.vuejs.org/guide/advanced/lazy-loading.html) to load your Vue components.

**Comment by xcsrz** [comment]
I ran into this problem as well.  I was able to get around it by using dynamic imports on all the components as the README outlines

https://github.com/cheap-glitch/vue-cli-plugin-sitemap/blob/main/README.md?plain=1#L88

However, this results in the entire compiled vue app being chunked into separate js for each route which is not optimal.  It's a tricky problem to solve however as the issue boils down to handling/expecting SFC syntax outside of vue.

**Comment by xcsrz** [comment]
This is very hacky, but I was able to create a workaround without granularly chunking my app up into individual pages with this update to `package.json`

```
"sitemap": "rm sitemap.xml && cat src/routes.ts | sed '/import/d' | sed '/component/d' > src/sitemap-routes.ts && vue-cli-service sitemap && rm src/sitemap-routes.ts"
``` 
and updating my `vue.config.js` file to use that temporary file:
```
const { routes } = require('./src/sitemap-routes.ts');
```

This of course requires your routes file be structured in a way where deleting the entire `import` and `component` lines will still yield valid JS/TS ... and requires `sed` so some windows users may not be able to use this approach without getting into that whole WSL thing.  

All in all this "solution" is only valid on personal (single dev) projects and not suitable for a team project.

**Comment by cheap-glitch** [comment]
> being chunked into separate js for each route which is not optimal

Why not? This is the recommended way to handle routes in any SPA that grows beyond a very simple prototype. It avoids loading the whole bundle when rendering a single page.

> This is very hacky, but I was able to create a workaround without granularly chunking my app

You might be interested in https://router.vuejs.org/guide/advanced/lazy-loading.html#grouping-components-in-the-same-chunk
