### ISSUE TITLE
Async slugs don't work.

### ISSUE THREAD

**Issue by Mozg1024** [cheap-glitch/vue-cli-plugin-sitemap#3]
> // Slugs can also be provided via an asynchronous function
> slugs: async () => [...await someAsyncCallToADatabase()]

This doesn't work because of validation:

```
const slugsSchema = {
	type:  'array',
        ...
```

**Comment by cheap-glitch** [comment]
This should be fixed in `2.0.0` (cf. the changelog [here](https://github.com/cheap-glitch/vue-cli-plugin-sitemap/releases/tag/v2.0.0)).
If you still encounter this bug after upgrading, feel free to reopen the issue.
